// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD2QOR_ZeHIVpuU-eAlh1JvTVHKmmNMvE',
    appId: '1:759887509780:web:1ff79fc4faf82055d66a01',
    messagingSenderId: '759887509780',
    projectId: 'english4community-4c654',
    authDomain: 'english4community-4c654.firebaseapp.com',
    storageBucket: 'english4community-4c654.firebasestorage.app',
    measurementId: 'G-E2M3W2G8W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9tn_HXRN4IMe6FCFcvJZVpjIIC_MoGbs',
    appId: '1:759887509780:android:606625f060f3d244d66a01',
    messagingSenderId: '759887509780',
    projectId: 'english4community-4c654',
    storageBucket: 'english4community-4c654.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzj5Go9TrxOHE_i4RfugUVMe6zXTS2dSI',
    appId: '1:313799665754:ios:3f78977440c37842d49063',
    messagingSenderId: '313799665754',
    projectId: 'first-flutter-1ccf4',
    storageBucket: 'first-flutter-1ccf4.firebasestorage.app',
    androidClientId: '313799665754-ik0ttr5go7lt9ta7g38riq9jijfnil47.apps.googleusercontent.com',
    iosClientId: '313799665754-pn465a95lh75lapqtj7fvurp7q53ohv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.recognizeFace',
  );
}