// app.js
import cors from 'cors';
import authRoutes from './src/routes/authRoutes.js';
import userRoutes from './src/routes/userRoutes.js';
import listeningRoutes from './src/routes/listeningRoutes.js';
import express from 'express';
import writingTopicRoutes from "./src/routes/writingTopicRoutes.js";
import speakingRoutes from "./src/routes/speakingRoutes.js";
import readingRoutes from "./src/routes/readingRoutes.js";
import vocabRoutes from "./src/routes/vocabRoutes.js";
import progressRoutes from "./src/routes/progressRoutes.js";
import chatRoutes from "./src/routes/chatRoutes.js";
import adminRoutes from "./src/routes/adminRoutes.js";
import reportRoutes from "./src/routes/reportRoutes.js";
import notificationRoutes from "./src/routes/notificationRoutes.js";
import listeningCompRoutes from "./src/routes/listeningCompRoutes.js";
import appVersionRoutes from "./src/routes/appVersionRoutes.js";
import adminAppReleaseRoutes from "./src/routes/adminAppReleaseRoutes.js";
import teacherRoutes from "./src/routes/teacherRoutes.js";
import classroomRoutes from "./src/routes/classroomRoutes.js";
import examRoutes from "./src/routes/examRoutes.js";
import classroomChatRoutes from "./src/routes/classroomChatRoutes.js";
import classroomChatRootRoutes from "./src/routes/classroomChatRootRoutes.js";
const app = express();

app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use('/api/auth', authRoutes);
app.use('/api/users', userRoutes);
app.use('/api/listening', listeningRoutes);
app.use('/api/writing', writingTopicRoutes);
app.use('/api/speaking', speakingRoutes);
app.use('/api/reading', readingRoutes);
app.use('/api/vocab', vocabRoutes);
app.use('/api/progress', progressRoutes);
app.use('/api/chat', chatRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/reports', reportRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/listening-comp', listeningCompRoutes);
app.use('/api/app', appVersionRoutes);
app.use('/api/admin/app-releases', adminAppReleaseRoutes);
app.use('/api/teacher', teacherRoutes);
app.use('/api/classrooms', classroomRoutes);
app.use('/api/exams', examRoutes);
app.use('/api/classroom-chat', classroomChatRootRoutes);
app.use('/api/classroom-chat/:classroomId', classroomChatRoutes);

export default app;
